RaspberryWebApp/Models/Relay.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RaspberryWebApp.Models
{

    public class Relay
    {
        public List<RelayEvent> RelayEvents { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public Guid DeviceID { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid ID { get; set; }

    }
}

RaspberryWebApp/Models/RelayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RaspberryWebApp.Models
{
    public class RelayViewModel
    {
        public Relay Relay { get; set; }
        public List<RelayEvent> RelayEvents { get; set; }

    }
}

RaspberryWebApp/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspberryWebApp.DAL;
using RaspberryWebApp.Models;

namespace RaspberryWebApp.Controllers
{
    public class DevicesController : Controller
    {
        private RaspContext db = new RaspContext();

        // GET: Devices
        public ActionResult Index()
        {
            return View(db.Devices.ToList());
        }

        // GET: Devices/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
        
        
            var relays = db.Relays.Include(c => c.RelayEvents).Where(x => x.DeviceID == id.Value).ToList<Relay>();


            device.Relays = relays;
            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,devicenumber,Name,IsSuccess")] Device device)
        {
            if (ModelState.IsValid)
            {
                device.ID = Guid.NewGuid();
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(device);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,devicenumber,Name,IsSuccess")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(device);
        }

        // GET: Devices/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspberryWebApp/Controllers/RelayEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspberryWebApp.DAL;
using RaspberryWebApp.Models;

namespace RaspberryWebApp.Controllers
{
    public class RelayEventsController : Controller
    {
        private RaspContext db = new RaspContext();


        // GET: RelayEvents/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            if (relayEvent == null)
            {
                return HttpNotFound();
            }
            return View(relayEvent);
        }

        // GET: RelayEvents/Create
        public ActionResult Create(Guid id)
        {
            ViewData["relayparentid"] = id;
            RelayEvent eventToCreate = new RelayEvent();
            eventToCreate.RelayID = id;
            eventToCreate.start = DateTime.Now;
            eventToCreate.duration = 1;
            eventToCreate.end = eventToCreate.start.AddMinutes(5);
            return View(eventToCreate);
        }

        // POST: RelayEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RelayID,start,duration,DurationType")] RelayEvent relayEvent)
        {
            if (ModelState.IsValid)
            {
                relayEvent.ID = Guid.NewGuid();
                int durationMultipler = 1;
                if (relayEvent.DurationType == "1")
                {
                    durationMultipler = 5;
                }
                else if (relayEvent.DurationType == "2")
                {
                    durationMultipler = 60;
                }
                relayEvent.end = relayEvent.start.AddMinutes(durationMultipler * relayEvent.duration);

                db.RelayEvents.Add(relayEvent);
                db.SaveChanges();

                return RedirectToAction("Details", "Relays", new { id = relayEvent.RelayID });

            }

            return View(relayEvent);
        }

        // GET: RelayEvents/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            if (relayEvent == null)
            {
                return HttpNotFound();
            }
            return View(relayEvent);
        }

        // POST: RelayEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RelayID,start,end,duration,DurationType")] RelayEvent relayEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relayEvent).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Details", "Relays", new { id = relayEvent.RelayID });


            }
            return View(relayEvent);
        }

        // GET: RelayEvents/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            if (relayEvent == null)
            {
                return HttpNotFound();
            }
            return View(relayEvent);
        }

        // POST: RelayEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            db.RelayEvents.Remove(relayEvent);
            db.SaveChanges();
            return RedirectToAction("Details", "Relays", new { id = relayEvent.RelayID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspberryWebApp/Controllers/RelaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspberryWebApp.DAL;
using RaspberryWebApp.Models;

namespace RaspberryWebApp.Controllers
{
    public class RelaysController : Controller
    {
        private RaspContext db = new RaspContext();

        // GET: Relays/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            DateTime todayZero = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            DateTime todayOne = todayZero.AddDays(1);

            var relayEvents = db.RelayEvents.Where(x => x.RelayID == relay.ID  && (  (x.start<=todayZero && x.end>=todayZero) || (x.end >=todayOne && x.start <=todayOne) || (x.start <= todayZero && x.end >= todayOne) || (x.start>=todayZero && x.end <todayOne) )).ToList<RelayEvent>();
            //&& (x.start <= todayZero && x.end >=todayZero
            relay.RelayEvents = relayEvents;
            return View(relay);
        }

        // GET: Relays/Create
        public ActionResult Create(Guid id)
        {         
            Relay relay = new Relay();         
            relay.DeviceID = id;
            return View(relay);
        }

        // POST: Relays/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,DeviceID")] Relay relay)
        {
            if (ModelState.IsValid)
            {
                relay.ID = Guid.NewGuid();
                relay.Index = GetFreeIndex(relay);
                db.Relays.Add(relay);
                db.SaveChanges();
                return RedirectToAction("Details", "Devices", new { id = relay.DeviceID });
            }

            return View(relay);
        }

        private int GetFreeIndex(Relay relay)
        {
            var relays = db.Relays.Where(x => x.DeviceID == relay.DeviceID).ToList<Relay>();

            for (int i = 0; i <= relays.Count(); i++)
            {
                if (!relays.Where(x => x.Index == i).Any())
                {
                    return i;
                }

            }

            return relays.Count()+1;
        }

        // GET: Relays/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            return View(relay);
        }

        // POST: Relays/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Index,Name,DeviceID")] Relay relay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Devices", new { id = relay.DeviceID });
            }
            return View(relay);
        }

        // GET: Relays/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            return View(relay);
        }

        // POST: Relays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Relay relay = db.Relays.Find(id);
            db.Relays.Remove(relay);
            db.SaveChanges();
            return RedirectToAction("Details", "Devices", new { id = relay.DeviceID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspberryWebApp/Views/Relays/Create.cshtml
@model RaspberryWebApp.Models.Relay

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @*@Html.Hidden("DeviceID", ViewData["deviceparentid"])*@
    @Html.Hidden("DeviceID", Model.DeviceID)
    <div class="form-horizontal">
        <h4>Relay</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

RaspberryWebApp/Views/Relays/Delete.cshtml
@model RaspberryWebApp.Models.Relay

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Relay</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Index)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Index)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceID)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" onclick="javascript: return confirm('Are you sure you wish to delete this item?');" />

        </div>
    }
</div>

RaspberryWebApp/Views/Relays/Details.cshtml
@using RaspberryWebApp.Models
@using Newtonsoft.Json
@model RaspberryWebApp.Models.Relay
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Relay</h4>
    <hr />
    @Html.ActionLink("Edit Relay", "Edit", new { id = Model.ID })


    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Index)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Index)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceID)
        </dd>
    </dl>


    <br />



    <table class="table">
        <tr>
            <th>
                start
            </th>
            <th>
                Duration
            </th>

            <th></th>
        </tr>

        @foreach (RelayEvent relayevent in Model.RelayEvents)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => relayevent.start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => relayevent.duration)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "RelayEvents", new { id = relayevent.ID }, null) |
                    @Html.ActionLink("Details", "Details", "RelayEvents", new { id = relayevent.ID }, null) |
                    @Html.ActionLink("Delete", "Delete", "RelayEvents", new { id = relayevent.ID }, null)
                </td>
            </tr>
        }

    </table>




    <br />
    @Html.ActionLink("+ RelayEvent", "Create", "RelayEvents", new { id = Model.ID }, null)
    <br />
</div>
<p>
    @Html.ActionLink("Back to List of relays", "Details", "Devices", new { id = Model.DeviceID }, null)
</p>

<div class="calendar template">
    <div style="height:300px;width:300px;">
        pondelok
    </div>

</div>
<script type="text/javascript">



$(document).ready(function () {
 
    var data = @Html.Raw(JsonConvert.SerializeObject(this.Model));
   
    var aaaa = $('#calendar template:first-child');

    });
</script>

RaspberryWebApp/Views/Relays/Edit.cshtml
@model RaspberryWebApp.Models.Relay

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Relay</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Index, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Index, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Index, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>