RaspberryWebApp/Models/Device.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RaspberryWebApp.Models
{
    public class Device
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid ID { get; set; }

        public int MaxRelays { get; set; }
        public int devicenumber { get; set; }
        public string Name { get; set; }
        public bool IsSuccess { get; set; }
        public List<Relay> Relays { get; set; }
        public Device()
        {
            Relays = new List<Relay>();
        }
    }
}

RaspberryWebApp/Models/DeviceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RaspberryWebApp.Models
{
    public class DeviceViewModel
    {

        public Device Device { get; set; }
        public List<Relay> Relays { get; set; }

    }
}

RaspberryWebApp/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspberryWebApp.DAL;
using RaspberryWebApp.Models;

namespace RaspberryWebApp.Controllers
{
    public class DevicesController : Controller
    {
        private RaspContext db = new RaspContext();

        // GET: Devices
        public ActionResult Index()
        {
            return View(db.Devices.ToList());
        }

        // GET: Devices/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
        
        
            var relays = db.Relays.Include(c => c.RelayEvents).Where(x => x.DeviceID == id.Value).ToList<Relay>();


            device.Relays = relays;
            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,devicenumber,Name,IsSuccess")] Device device)
        {
            if (ModelState.IsValid)
            {
                device.ID = Guid.NewGuid();
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(device);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,devicenumber,Name,IsSuccess")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(device);
        }

        // GET: Devices/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspberryWebApp/Controllers/RelaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspberryWebApp.DAL;
using RaspberryWebApp.Models;

namespace RaspberryWebApp.Controllers
{
    public class RelaysController : Controller
    {
        private RaspContext db = new RaspContext();

        // GET: Relays/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            DateTime todayZero = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            DateTime todayOne = todayZero.AddDays(1);

            var relayEvents = db.RelayEvents.Where(x => x.RelayID == relay.ID  && (  (x.start<=todayZero && x.end>=todayZero) || (x.end >=todayOne && x.start <=todayOne) || (x.start <= todayZero && x.end >= todayOne) || (x.start>=todayZero && x.end <todayOne) )).ToList<RelayEvent>();
            //&& (x.start <= todayZero && x.end >=todayZero
            relay.RelayEvents = relayEvents;
            return View(relay);
        }

        // GET: Relays/Create
        public ActionResult Create(Guid id)
        {         
            Relay relay = new Relay();         
            relay.DeviceID = id;
            return View(relay);
        }

        // POST: Relays/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,DeviceID")] Relay relay)
        {
            if (ModelState.IsValid)
            {
                relay.ID = Guid.NewGuid();
                relay.Index = GetFreeIndex(relay);
                db.Relays.Add(relay);
                db.SaveChanges();
                return RedirectToAction("Details", "Devices", new { id = relay.DeviceID });
            }

            return View(relay);
        }

        private int GetFreeIndex(Relay relay)
        {
            var relays = db.Relays.Where(x => x.DeviceID == relay.DeviceID).ToList<Relay>();

            for (int i = 0; i <= relays.Count(); i++)
            {
                if (!relays.Where(x => x.Index == i).Any())
                {
                    return i;
                }

            }

            return relays.Count()+1;
        }

        // GET: Relays/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            return View(relay);
        }

        // POST: Relays/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Index,Name,DeviceID")] Relay relay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Devices", new { id = relay.DeviceID });
            }
            return View(relay);
        }

        // GET: Relays/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            return View(relay);
        }

        // POST: Relays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Relay relay = db.Relays.Find(id);
            db.Relays.Remove(relay);
            db.SaveChanges();
            return RedirectToAction("Details", "Devices", new { id = relay.DeviceID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspberryWebApp/Views/Devices/Create.cshtml
@model RaspberryWebApp.Models.Device

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Device</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.devicenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.devicenumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.devicenumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSuccess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSuccess)
                    @Html.ValidationMessageFor(model => model.IsSuccess, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.RelayCount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                        @Html.EditorFor(model => model.RelayCount)
                        @Html.ValidationMessageFor(model => model.RelayCount, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RaspberryWebApp/Views/Devices/Delete.cshtml
@model RaspberryWebApp.Models.Device

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.devicenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.devicenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSuccess)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSuccess)
        </dd>
        @*<dt>
                @Html.DisplayNameFor(model => model.RelayCount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RelayCount)
            </dd>*@

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" onclick="javascript: return confirm('Are you sure you wish to delete this item?');" />
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RaspberryWebApp/Views/Devices/Details.cshtml
@using RaspberryWebApp.Models
@using Newtonsoft.Json
@model RaspberryWebApp.Models.Device

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.devicenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.devicenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <div>
        Following relays are found in system
    </div>
    <p>
        <table class="table">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Index
                </th>

                <th></th>
                <th></th>
            </tr>

            @foreach (Relay relay in Model.Relays)
            {

               
                <tr>
                    <td>
                        @*@foreach (RelayEvent relayEvent in relay.RelayEvents)
                        {
                            @Html.DisplayFor(modelItem => relayEvent.start)
                        }*@
                        @Html.DisplayFor(modelItem => relay.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => relay.Index)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Relays", new { id = relay.ID }, null)
                        @Html.ActionLink("Details", "Details", "Relays", new { id = relay.ID }, null)
                        @Html.ActionLink("Delete", "Delete", "Relays", new { id = relay.ID }, null)
                    </td>
                    <td>
                        <canvas id="myCanvas" width="200" height="20" style="border:1px solid #000000;">
                            Your browser does not support the HTML5 canvas tag.
                        </canvas>
                    </td>
</tr>
            }
        </table>
    </p>
</div>
@*@if (Model.Relays != null && Model.Relays.Count() < Model.Device.RelayCount)
    {*@

@Html.ActionLink("+ Relay", "Create", "Relays", new { id = Model.ID }, null)

@*}*@
<p>
    @Html.ActionLink("Edit Device", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back All Devices", "Index")
</p>

@*<div class="calendar-template">
    <div class="sampleRow" style="height:300px;width:300px;">
        pondelok
    </div>
</div>
<div class="calendar-renderer">

</div>*@

<script type="text/javascript">

    function RenderRelayDay(relay)
    {

        var validRelayEvents = [];
        for(i=0;i< relay.RelayEvents.length;i++)
        {
          
            var relayEvent = relay.RelayEvents[i];
            var currentStartDate = new Date(relayEvent.start);
            var currentEndDate = new Date(relayEvent.end);

            var today =   new Date();
            var todayZero = new Date(today.getYear()+1900,today.getMonth(), today.getDate());


            if(todayZero.getTime() >=  currentStartDate.getTime() || todayZero.getTime() <=  currentEndDate.getTime())
            {
                validRelayEvents.push(relayEvent);
            }
        }

        

    }

$(document).ready(function () {

    var data = @Html.Raw(JsonConvert.SerializeObject(this.Model));  
  
    //var $button = $('.calendar-template').find('.sampleRow').clone();
    //$('.calendar-renderer').append($button);
  
    //var aaa = JSON.stringify(data);
    //var aa="";

    
    for(i=0;i< data.Relays.length;i++){

        RenderRelayDay(data.Relays[i]);

    }

    });
</script>

RaspberryWebApp/Views/Devices/Edit.cshtml
@model RaspberryWebApp.Models.Device

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Device</h4>
        <hr />
        @*@Html.Hidden("RelayCount", Model.RelayCount)*@

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.devicenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.devicenumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.devicenumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSuccess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSuccess)
                    @Html.ValidationMessageFor(model => model.IsSuccess, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RaspberryWebApp/Views/Devices/Index.cshtml
@model IEnumerable<RaspberryWebApp.Models.Device>

@{
    ViewBag.Title = "Helo here are all devices in our cloud";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Device", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.devicenumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.RelayCount)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.devicenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.RelayCount)
                </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>
<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker(
                {
               
                }
                    );
            });
        </script>
    </div>
</div>